//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFA_SimaFlex_MP_Stock
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articles
    {
        public int IdArticles { get; set; }
        public string Référence { get; set; }
        public string Couleur { get; set; }
    
        public virtual Catégories Catégories { get; set; }
        public virtual Commandes Commandes { get; set; }
    }
}
