//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFA_SimaFlex_MP_Stock
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fournisseurs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fournisseurs()
        {
            this.Commandes = new HashSet<Commandes>();
        }
    
        public int IdFournisseurs { get; set; }
        public string Nom { get; set; }
        public string Adresse { get; set; }
        public string Tél_Pérsonnel { get; set; }
        public string Tél_Travail { get; set; }
        public string Tél_fixe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Commandes> Commandes { get; set; }
        public virtual Catégories Catégories { get; set; }
    }
}
