//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFA_SimaFlex_MP_Stock
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelStockContainer : DbContext
    {
        public ModelStockContainer()
            : base("name=ModelStockContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Articles> ArticlesSet { get; set; }
        public virtual DbSet<Catégories> CatégoriesSet { get; set; }
        public virtual DbSet<Sous_Catégories> Sous_CatégoriesSet { get; set; }
        public virtual DbSet<Commandes> CommandesSet { get; set; }
        public virtual DbSet<Fournisseurs> FournisseursSet { get; set; }
    }
}
