//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFA_SimaFlex_MP_Stock
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sous_Catégories
    {
        public int IdSous_Catégories { get; set; }
        public string Type_Sous_Catégorie { get; set; }
    
        public virtual Catégories Catégories { get; set; }
    }
}
